# Generated by Django 3.1.3 on 2022-03-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_svc', '0002_auto_20220131_1806'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='discountcode',
            name='discount_sv_status_0d3be2_idx',
        ),
        migrations.RemoveIndex(
            model_name='discountcode',
            name='discount_sv_campaig_eb1c1c_idx',
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['status'], name='dummy_svc_d_status_13f152_idx'),
        ),
        migrations.AddIndex(
            model_name='discountcode',
            index=models.Index(fields=['campaign_id'], name='dummy_svc_d_campaig_d1fea3_idx'),
        ),
    ]
